// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC20FlashMint$Type } from "./ERC20FlashMint";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC20FlashMint"]: ERC20FlashMint$Type;
    ["@openzeppelin/contracts/token/ERC20/extensions/ERC20FlashMint.sol:ERC20FlashMint"]: ERC20FlashMint$Type;
  }

  interface ContractTypesMap {
    ["ERC20FlashMint"]: GetContractReturnType<ERC20FlashMint$Type["abi"]>;
    ["@openzeppelin/contracts/token/ERC20/extensions/ERC20FlashMint.sol:ERC20FlashMint"]: GetContractReturnType<ERC20FlashMint$Type["abi"]>;
  }
}
