// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC1363Utils$Type } from "./ERC1363Utils";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC1363Utils"]: ERC1363Utils$Type;
    ["@openzeppelin/contracts/token/ERC20/utils/ERC1363Utils.sol:ERC1363Utils"]: ERC1363Utils$Type;
  }

  interface ContractTypesMap {
    ["ERC1363Utils"]: GetContractReturnType<ERC1363Utils$Type["abi"]>;
    ["@openzeppelin/contracts/token/ERC20/utils/ERC1363Utils.sol:ERC1363Utils"]: GetContractReturnType<ERC1363Utils$Type["abi"]>;
  }
}
