// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IERC1363Spender$Type } from "./IERC1363Spender";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC1363Spender"]: IERC1363Spender$Type;
    ["@openzeppelin/contracts/interfaces/IERC1363Spender.sol:IERC1363Spender"]: IERC1363Spender$Type;
  }

  interface ContractTypesMap {
    ["IERC1363Spender"]: GetContractReturnType<IERC1363Spender$Type["abi"]>;
    ["@openzeppelin/contracts/interfaces/IERC1363Spender.sol:IERC1363Spender"]: GetContractReturnType<IERC1363Spender$Type["abi"]>;
  }
}
