// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IERC1363Receiver$Type } from "./IERC1363Receiver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC1363Receiver"]: IERC1363Receiver$Type;
    ["@openzeppelin/contracts/interfaces/IERC1363Receiver.sol:IERC1363Receiver"]: IERC1363Receiver$Type;
  }

  interface ContractTypesMap {
    ["IERC1363Receiver"]: GetContractReturnType<IERC1363Receiver$Type["abi"]>;
    ["@openzeppelin/contracts/interfaces/IERC1363Receiver.sol:IERC1363Receiver"]: GetContractReturnType<IERC1363Receiver$Type["abi"]>;
  }
}
