// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IERC3156FlashBorrower$Type } from "./IERC3156FlashBorrower";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC3156FlashBorrower"]: IERC3156FlashBorrower$Type;
    ["@openzeppelin/contracts/interfaces/IERC3156FlashBorrower.sol:IERC3156FlashBorrower"]: IERC3156FlashBorrower$Type;
  }

  interface ContractTypesMap {
    ["IERC3156FlashBorrower"]: GetContractReturnType<IERC3156FlashBorrower$Type["abi"]>;
    ["@openzeppelin/contracts/interfaces/IERC3156FlashBorrower.sol:IERC3156FlashBorrower"]: GetContractReturnType<IERC3156FlashBorrower$Type["abi"]>;
  }
}
