// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC1363$Type } from "./ERC1363";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC1363"]: ERC1363$Type;
    ["@openzeppelin/contracts/token/ERC20/extensions/ERC1363.sol:ERC1363"]: ERC1363$Type;
  }

  interface ContractTypesMap {
    ["ERC1363"]: GetContractReturnType<ERC1363$Type["abi"]>;
    ["@openzeppelin/contracts/token/ERC20/extensions/ERC1363.sol:ERC1363"]: GetContractReturnType<ERC1363$Type["abi"]>;
  }
}
