// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IERC3156FlashLender$Type } from "./IERC3156FlashLender";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC3156FlashLender"]: IERC3156FlashLender$Type;
    ["@openzeppelin/contracts/interfaces/IERC3156FlashLender.sol:IERC3156FlashLender"]: IERC3156FlashLender$Type;
  }

  interface ContractTypesMap {
    ["IERC3156FlashLender"]: GetContractReturnType<IERC3156FlashLender$Type["abi"]>;
    ["@openzeppelin/contracts/interfaces/IERC3156FlashLender.sol:IERC3156FlashLender"]: GetContractReturnType<IERC3156FlashLender$Type["abi"]>;
  }
}
